# Base image
FROM node:16-alpine

# Set working directory
WORKDIR /app

# Copy package.json and possibly package-lock.json or yarn.lock
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy your server code
COPY . .

# Build your TypeScript files if necessary
RUN npm run build-server

# Expose the server port
EXPOSE 8081

# Command to run your server
CMD ["node", "dist/server.js"]
